### ISSUE TITLE
Create gcp infrastructure

### ISSUE THREAD

**Issue by ital0sant0s** [nearform/gh-issues-finder#3]
The necessary infra are the following

- Service Account
- Secrets Manager
- Cloud Run

**Comment by simoneb** [comment]
Do we need secrets?

**Comment by simoneb** [comment]
to deploy let's use oidc. we've done this elsewhere, e.g. https://github.com/nearform/zoom-shuffle-bot/blob/master/.github/workflows/cd.yml#L41
